[versions]
adventure = "5.2.0"
slf4j = "2.0.18"
gson = "2.14.0"
junit = "6.0.0"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
